name: GitHub Actions

on:
  workflow_dispatch:

env:
  NODE_ENV: ${{ secrets.NODE_ENV }}

  WALLET_PRIVATE_KEY_DEV1: ${{ secrets.WALLET_PRIVATE_KEY_DEV1 }}
  WALLET_PUBLIC_KEY_DEV1: ${{ secrets.WALLET_PUBLIC_KEY_DEV1 }}
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
  OP_ETHERSCAN_API_KEY: ${{ secrets.OP_ETHERSCAN_API_KEY }}
  POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}

  IPFS_URL: ${{ secrets.IPFS_URL }}
  IPFS_USER: ${{ secrets.IPFS_USER }}
  IPFS_PASS: ${{ secrets.IPFS_PASS }}
  IPNS_KEY: ${{ secrets.IPNS_KEY }}

jobs:
  Build-and-Publish:
    if: |
      ${{ github.event_name == 'workflow_dispatch' }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.0'
          cache: 'yarn'

      - name: Install node_modules
        run: |
          yarn install

      - name: Generate and publish stats
        run: |
          CI=false yarn run op:generate-stats
